package openFactions;

public enum Can {
	ASSIGN_GROUPS,	
	CHANGE_FACTION_DESC,	
	CHANGE_FACTION_NAME,	
	CLAIM,	
	DISBAND,
	EDIT_CLAIM,	
	EDIT_CLAIM_SETTINGS,
	EDIT_GROUPS,
	OVERRIDE_CLAIM_SETTINGS,
	KICK,	
	MAKE_OR_REMOVE_GROUPS,
	SET_VISA,
	UNCLAIM,	
	UNCLAIM_ALL
}
